// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package sledgconf_demo_proto_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Enums
type DataType int32

const (
	DataType_WaterLevel          DataType = 0
	DataType_AirTemperature      DataType = 1
	DataType_WaterTemperature    DataType = 2
	DataType_Wind                DataType = 3
	DataType_AirPressure         DataType = 4
	DataType_AirGap              DataType = 5
	DataType_Conductivity        DataType = 6
	DataType_Visibility          DataType = 7
	DataType_Humidity            DataType = 8
	DataType_Salinity            DataType = 9
	DataType_HourlyHeight        DataType = 10
	DataType_HighLow             DataType = 11
	DataType_DailyMean           DataType = 12
	DataType_MonthlyMean         DataType = 13
	DataType_OneMinuteWaterLevel DataType = 14
	DataType_Preditions          DataType = 15
	DataType_Datums              DataType = 16
	DataType_Currents            DataType = 17
	DataType_CurrentsPredictions DataType = 18
)

var DataType_name = map[int32]string{
	0:  "WaterLevel",
	1:  "AirTemperature",
	2:  "WaterTemperature",
	3:  "Wind",
	4:  "AirPressure",
	5:  "AirGap",
	6:  "Conductivity",
	7:  "Visibility",
	8:  "Humidity",
	9:  "Salinity",
	10: "HourlyHeight",
	11: "HighLow",
	12: "DailyMean",
	13: "MonthlyMean",
	14: "OneMinuteWaterLevel",
	15: "Preditions",
	16: "Datums",
	17: "Currents",
	18: "CurrentsPredictions",
}
var DataType_value = map[string]int32{
	"WaterLevel":          0,
	"AirTemperature":      1,
	"WaterTemperature":    2,
	"Wind":                3,
	"AirPressure":         4,
	"AirGap":              5,
	"Conductivity":        6,
	"Visibility":          7,
	"Humidity":            8,
	"Salinity":            9,
	"HourlyHeight":        10,
	"HighLow":             11,
	"DailyMean":           12,
	"MonthlyMean":         13,
	"OneMinuteWaterLevel": 14,
	"Preditions":          15,
	"Datums":              16,
	"Currents":            17,
	"CurrentsPredictions": 18,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}
func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_demo_744868870d596b95, []int{0}
}

type MetricPreference int32

const (
	MetricPreference_English MetricPreference = 0
	MetricPreference_Metric  MetricPreference = 1
)

var MetricPreference_name = map[int32]string{
	0: "English",
	1: "Metric",
}
var MetricPreference_value = map[string]int32{
	"English": 0,
	"Metric":  1,
}

func (x MetricPreference) String() string {
	return proto.EnumName(MetricPreference_name, int32(x))
}
func (MetricPreference) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_demo_744868870d596b95, []int{1}
}

// Message Definitions
type GetDataFromStationsRequest struct {
	ArrayOfStationIDs       []string         `protobuf:"bytes,1,rep,name=arrayOfStationIDs,proto3" json:"arrayOfStationIDs,omitempty"`
	StartTimeEpochInSeconds int64            `protobuf:"varint,2,opt,name=startTimeEpochInSeconds,proto3" json:"startTimeEpochInSeconds,omitempty"`
	EndTimeEpochInSeconds   int64            `protobuf:"varint,3,opt,name=endTimeEpochInSeconds,proto3" json:"endTimeEpochInSeconds,omitempty"`
	Datum                   string           `protobuf:"bytes,4,opt,name=datum,proto3" json:"datum,omitempty"`
	MetricPreference        MetricPreference `protobuf:"varint,5,opt,name=MetricPreference,proto3,enum=MetricPreference" json:"MetricPreference,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}         `json:"-"`
	XXX_unrecognized        []byte           `json:"-"`
	XXX_sizecache           int32            `json:"-"`
}

func (m *GetDataFromStationsRequest) Reset()         { *m = GetDataFromStationsRequest{} }
func (m *GetDataFromStationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDataFromStationsRequest) ProtoMessage()    {}
func (*GetDataFromStationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_744868870d596b95, []int{0}
}
func (m *GetDataFromStationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataFromStationsRequest.Unmarshal(m, b)
}
func (m *GetDataFromStationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataFromStationsRequest.Marshal(b, m, deterministic)
}
func (dst *GetDataFromStationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataFromStationsRequest.Merge(dst, src)
}
func (m *GetDataFromStationsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDataFromStationsRequest.Size(m)
}
func (m *GetDataFromStationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataFromStationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataFromStationsRequest proto.InternalMessageInfo

func (m *GetDataFromStationsRequest) GetArrayOfStationIDs() []string {
	if m != nil {
		return m.ArrayOfStationIDs
	}
	return nil
}

func (m *GetDataFromStationsRequest) GetStartTimeEpochInSeconds() int64 {
	if m != nil {
		return m.StartTimeEpochInSeconds
	}
	return 0
}

func (m *GetDataFromStationsRequest) GetEndTimeEpochInSeconds() int64 {
	if m != nil {
		return m.EndTimeEpochInSeconds
	}
	return 0
}

func (m *GetDataFromStationsRequest) GetDatum() string {
	if m != nil {
		return m.Datum
	}
	return ""
}

func (m *GetDataFromStationsRequest) GetMetricPreference() MetricPreference {
	if m != nil {
		return m.MetricPreference
	}
	return MetricPreference_English
}

type GetDataFromStationsResponse struct {
	MapOfStationData     map[string]*Station `protobuf:"bytes,1,rep,name=mapOfStationData,proto3" json:"mapOfStationData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetDataFromStationsResponse) Reset()         { *m = GetDataFromStationsResponse{} }
func (m *GetDataFromStationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataFromStationsResponse) ProtoMessage()    {}
func (*GetDataFromStationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_744868870d596b95, []int{1}
}
func (m *GetDataFromStationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataFromStationsResponse.Unmarshal(m, b)
}
func (m *GetDataFromStationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataFromStationsResponse.Marshal(b, m, deterministic)
}
func (dst *GetDataFromStationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataFromStationsResponse.Merge(dst, src)
}
func (m *GetDataFromStationsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataFromStationsResponse.Size(m)
}
func (m *GetDataFromStationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataFromStationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataFromStationsResponse proto.InternalMessageInfo

func (m *GetDataFromStationsResponse) GetMapOfStationData() map[string]*Station {
	if m != nil {
		return m.MapOfStationData
	}
	return nil
}

type ProductDataValues struct {
	Metadata             *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Data                 []*Data   `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	DataType             DataType  `protobuf:"varint,3,opt,name=dataType,proto3,enum=DataType" json:"dataType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProductDataValues) Reset()         { *m = ProductDataValues{} }
func (m *ProductDataValues) String() string { return proto.CompactTextString(m) }
func (*ProductDataValues) ProtoMessage()    {}
func (*ProductDataValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_744868870d596b95, []int{2}
}
func (m *ProductDataValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductDataValues.Unmarshal(m, b)
}
func (m *ProductDataValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductDataValues.Marshal(b, m, deterministic)
}
func (dst *ProductDataValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductDataValues.Merge(dst, src)
}
func (m *ProductDataValues) XXX_Size() int {
	return xxx_messageInfo_ProductDataValues.Size(m)
}
func (m *ProductDataValues) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductDataValues.DiscardUnknown(m)
}

var xxx_messageInfo_ProductDataValues proto.InternalMessageInfo

func (m *ProductDataValues) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ProductDataValues) GetData() []*Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ProductDataValues) GetDataType() DataType {
	if m != nil {
		return m.DataType
	}
	return DataType_WaterLevel
}

type Metadata struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lon                  string   `protobuf:"bytes,3,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat                  string   `protobuf:"bytes,4,opt,name=lat,proto3" json:"lat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_744868870d596b95, []int{3}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (dst *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(dst, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Metadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metadata) GetLon() string {
	if m != nil {
		return m.Lon
	}
	return ""
}

func (m *Metadata) GetLat() string {
	if m != nil {
		return m.Lat
	}
	return ""
}

type Data struct {
	T                    string   `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"`
	V                    string   `protobuf:"bytes,2,opt,name=v,proto3" json:"v,omitempty"`
	F                    string   `protobuf:"bytes,3,opt,name=f,proto3" json:"f,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_744868870d596b95, []int{4}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (dst *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(dst, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetT() string {
	if m != nil {
		return m.T
	}
	return ""
}

func (m *Data) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func (m *Data) GetF() string {
	if m != nil {
		return m.F
	}
	return ""
}

type Station struct {
	StationID            string                        `protobuf:"bytes,1,opt,name=stationID,proto3" json:"stationID,omitempty"`
	ProductData          map[string]*ProductDataValues `protobuf:"bytes,2,rep,name=productData,proto3" json:"productData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Station) Reset()         { *m = Station{} }
func (m *Station) String() string { return proto.CompactTextString(m) }
func (*Station) ProtoMessage()    {}
func (*Station) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_744868870d596b95, []int{5}
}
func (m *Station) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Station.Unmarshal(m, b)
}
func (m *Station) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Station.Marshal(b, m, deterministic)
}
func (dst *Station) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Station.Merge(dst, src)
}
func (m *Station) XXX_Size() int {
	return xxx_messageInfo_Station.Size(m)
}
func (m *Station) XXX_DiscardUnknown() {
	xxx_messageInfo_Station.DiscardUnknown(m)
}

var xxx_messageInfo_Station proto.InternalMessageInfo

func (m *Station) GetStationID() string {
	if m != nil {
		return m.StationID
	}
	return ""
}

func (m *Station) GetProductData() map[string]*ProductDataValues {
	if m != nil {
		return m.ProductData
	}
	return nil
}

func init() {
	proto.RegisterType((*GetDataFromStationsRequest)(nil), "GetDataFromStationsRequest")
	proto.RegisterType((*GetDataFromStationsResponse)(nil), "GetDataFromStationsResponse")
	proto.RegisterMapType((map[string]*Station)(nil), "GetDataFromStationsResponse.MapOfStationDataEntry")
	proto.RegisterType((*ProductDataValues)(nil), "ProductDataValues")
	proto.RegisterType((*Metadata)(nil), "Metadata")
	proto.RegisterType((*Data)(nil), "Data")
	proto.RegisterType((*Station)(nil), "Station")
	proto.RegisterMapType((map[string]*ProductDataValues)(nil), "Station.ProductDataEntry")
	proto.RegisterEnum("DataType", DataType_name, DataType_value)
	proto.RegisterEnum("MetricPreference", MetricPreference_name, MetricPreference_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExampleReddiyoGRPCServiceClient is the client API for ExampleReddiyoGRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExampleReddiyoGRPCServiceClient interface {
	// Single Function that will get the data
	GetDataFromStations(ctx context.Context, in *GetDataFromStationsRequest, opts ...grpc.CallOption) (*GetDataFromStationsResponse, error)
}

type exampleReddiyoGRPCServiceClient struct {
	cc *grpc.ClientConn
}

func NewExampleReddiyoGRPCServiceClient(cc *grpc.ClientConn) ExampleReddiyoGRPCServiceClient {
	return &exampleReddiyoGRPCServiceClient{cc}
}

func (c *exampleReddiyoGRPCServiceClient) GetDataFromStations(ctx context.Context, in *GetDataFromStationsRequest, opts ...grpc.CallOption) (*GetDataFromStationsResponse, error) {
	out := new(GetDataFromStationsResponse)
	err := c.cc.Invoke(ctx, "/ExampleReddiyoGRPCService/GetDataFromStations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleReddiyoGRPCServiceServer is the server API for ExampleReddiyoGRPCService service.
type ExampleReddiyoGRPCServiceServer interface {
	// Single Function that will get the data
	GetDataFromStations(context.Context, *GetDataFromStationsRequest) (*GetDataFromStationsResponse, error)
}

func RegisterExampleReddiyoGRPCServiceServer(s *grpc.Server, srv ExampleReddiyoGRPCServiceServer) {
	s.RegisterService(&_ExampleReddiyoGRPCService_serviceDesc, srv)
}

func _ExampleReddiyoGRPCService_GetDataFromStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataFromStationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleReddiyoGRPCServiceServer).GetDataFromStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExampleReddiyoGRPCService/GetDataFromStations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleReddiyoGRPCServiceServer).GetDataFromStations(ctx, req.(*GetDataFromStationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExampleReddiyoGRPCService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ExampleReddiyoGRPCService",
	HandlerType: (*ExampleReddiyoGRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDataFromStations",
			Handler:    _ExampleReddiyoGRPCService_GetDataFromStations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_demo_744868870d596b95) }

var fileDescriptor_demo_744868870d596b95 = []byte{
	// 748 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x0e, 0xf5, 0x63, 0x8b, 0x23, 0x47, 0x59, 0x4f, 0x12, 0x58, 0x76, 0x82, 0xc2, 0x10, 0x50,
	0x40, 0x48, 0x6b, 0xa2, 0x55, 0x7b, 0x08, 0x5a, 0xf4, 0xe0, 0xda, 0xae, 0x1d, 0x20, 0x42, 0x04,
	0xda, 0x48, 0x80, 0x1e, 0x0a, 0x6c, 0xc4, 0x91, 0xb5, 0x28, 0xb9, 0x64, 0x77, 0x97, 0x6a, 0x09,
	0xf4, 0x1d, 0xfa, 0x3a, 0x7d, 0x80, 0x1e, 0xfb, 0x50, 0xc5, 0xac, 0x28, 0x47, 0xb5, 0x94, 0x9c,
	0x34, 0x7f, 0xdf, 0xc7, 0x6f, 0x66, 0xb4, 0x03, 0x90, 0x50, 0x96, 0x47, 0x85, 0xc9, 0x5d, 0x3e,
	0xf8, 0xab, 0x01, 0x47, 0x97, 0xe4, 0xce, 0xa5, 0x93, 0x3f, 0x99, 0x3c, 0xbb, 0x76, 0xd2, 0xa9,
	0x5c, 0xdb, 0x98, 0x7e, 0x2b, 0xc9, 0x3a, 0xfc, 0x12, 0xf6, 0xa5, 0x31, 0xb2, 0x7a, 0x33, 0xab,
	0x33, 0xaf, 0xce, 0x6d, 0x3f, 0x38, 0x6e, 0x0e, 0xc3, 0x78, 0x33, 0x81, 0x2f, 0xe1, 0xc0, 0x3a,
	0x69, 0xdc, 0x8d, 0xca, 0xe8, 0xa2, 0xc8, 0xa7, 0xf3, 0x57, 0xfa, 0x9a, 0xa6, 0xb9, 0x4e, 0x6c,
	0xbf, 0x71, 0x1c, 0x0c, 0x9b, 0xf1, 0xc7, 0xd2, 0xf8, 0x2d, 0x3c, 0x25, 0x9d, 0x6c, 0xc1, 0x35,
	0x3d, 0x6e, 0x7b, 0x12, 0x9f, 0x40, 0x3b, 0x91, 0xae, 0xcc, 0xfa, 0xad, 0xe3, 0x60, 0x18, 0xc6,
	0x4b, 0x07, 0x7f, 0x00, 0x31, 0x26, 0x67, 0xd4, 0x74, 0x62, 0x68, 0x46, 0x86, 0xf4, 0x94, 0xfa,
	0xed, 0xe3, 0x60, 0xd8, 0x1b, 0xed, 0x47, 0xf7, 0x13, 0xf1, 0x46, 0xe9, 0xe0, 0xdf, 0x00, 0x9e,
	0x6d, 0x9d, 0x88, 0x2d, 0x72, 0x6d, 0x09, 0x7f, 0x01, 0x91, 0xc9, 0xe2, 0xae, 0x6f, 0xae, 0xf3,
	0x13, 0xe9, 0x8e, 0x46, 0xd1, 0x27, 0x70, 0xd1, 0xf8, 0x1e, 0xe8, 0x42, 0x3b, 0x53, 0xc5, 0x1b,
	0x5c, 0x47, 0x63, 0x78, 0xba, 0xb5, 0x14, 0x05, 0x34, 0x7f, 0xa5, 0xaa, 0x1f, 0xf8, 0x5e, 0xd9,
	0xc4, 0xcf, 0xa0, 0xbd, 0x90, 0x69, 0x49, 0x7e, 0xba, 0xdd, 0x51, 0x27, 0xaa, 0x31, 0xf1, 0x32,
	0xfc, 0x5d, 0xe3, 0x65, 0x30, 0xf8, 0x13, 0xf6, 0x27, 0x26, 0x4f, 0xca, 0xa9, 0x57, 0xf6, 0x96,
	0xe3, 0x16, 0x3f, 0x87, 0x4e, 0x46, 0x4e, 0x26, 0x4b, 0xed, 0x8c, 0x0d, 0x79, 0x34, 0x3e, 0x10,
	0xdf, 0xa5, 0xf0, 0x10, 0x5a, 0xbe, 0xa4, 0xe1, 0xdb, 0x6b, 0x47, 0xcc, 0x10, 0xfb, 0x10, 0x33,
	0xf0, 0xef, 0x4d, 0x55, 0x90, 0xdf, 0x51, 0x6f, 0x14, 0xfa, 0x34, 0x07, 0xe2, 0xbb, 0xd4, 0x20,
	0x86, 0xce, 0x8a, 0x17, 0x7b, 0xd0, 0x50, 0x49, 0x2d, 0xbf, 0xa1, 0x12, 0x44, 0x68, 0x69, 0x99,
	0x2d, 0xc5, 0x87, 0xb1, 0xb7, 0xb9, 0xc7, 0x34, 0xd7, 0x9e, 0x31, 0x8c, 0xd9, 0xf4, 0x11, 0xe9,
	0xea, 0x0d, 0xb3, 0x39, 0xf8, 0x0a, 0x5a, 0xfc, 0x25, 0xdc, 0x83, 0xc0, 0xd5, 0x74, 0x81, 0x63,
	0x6f, 0x51, 0x53, 0x05, 0x0b, 0xf6, 0x66, 0x35, 0x4b, 0x30, 0x1b, 0xfc, 0x1d, 0xc0, 0x6e, 0x3d,
	0x1a, 0x7c, 0x0e, 0xa1, 0x5d, 0xfd, 0x63, 0x6b, 0xf4, 0x87, 0x00, 0x7e, 0x0f, 0xdd, 0xe2, 0xc3,
	0xb4, 0xea, 0xc6, 0x0f, 0x57, 0x73, 0x8d, 0xd6, 0x26, 0xb9, 0x5c, 0xdf, 0x7a, 0xf5, 0x51, 0x0c,
	0xe2, 0x7e, 0xc1, 0x96, 0xa5, 0x0d, 0xff, 0xbf, 0x34, 0x8c, 0x36, 0xd6, 0xb3, 0xb6, 0xbe, 0x17,
	0xff, 0x34, 0xa0, 0xb3, 0x9a, 0x2b, 0xf6, 0x00, 0xde, 0x49, 0x47, 0xe6, 0x35, 0x2d, 0x28, 0x15,
	0x0f, 0x10, 0xa1, 0x77, 0xaa, 0xcc, 0x0d, 0x65, 0x05, 0x19, 0xe9, 0x4a, 0x43, 0x22, 0xc0, 0x27,
	0x20, 0x7c, 0xcd, 0x7a, 0xb4, 0x81, 0x1d, 0x68, 0xbd, 0x53, 0x3a, 0x11, 0x4d, 0x7c, 0x04, 0xdd,
	0x53, 0x65, 0x26, 0x86, 0xac, 0xe5, 0x54, 0x0b, 0x01, 0x76, 0x4e, 0x95, 0xb9, 0x94, 0x85, 0x68,
	0xa3, 0x80, 0xbd, 0xb3, 0x5c, 0xb3, 0x1a, 0xb5, 0x50, 0xae, 0x12, 0x3b, 0xfc, 0xc9, 0xb7, 0xca,
	0xaa, 0xf7, 0x2a, 0x65, 0x7f, 0x17, 0xf7, 0xa0, 0x73, 0x55, 0x66, 0x2a, 0x61, 0xaf, 0xc3, 0xde,
	0xb5, 0x4c, 0x95, 0x66, 0x2f, 0x64, 0xf4, 0x55, 0x5e, 0x9a, 0xb4, 0xba, 0x22, 0x75, 0x3b, 0x77,
	0x02, 0xb0, 0x0b, 0xbb, 0x57, 0xea, 0x76, 0xfe, 0x3a, 0xff, 0x5d, 0x74, 0xf1, 0x21, 0x84, 0xe7,
	0x52, 0xa5, 0xd5, 0x98, 0xa4, 0x16, 0x7b, 0x2c, 0x64, 0x9c, 0x6b, 0x37, 0xaf, 0x03, 0x0f, 0xf1,
	0x00, 0x1e, 0xbf, 0xd1, 0x34, 0x56, 0xba, 0x74, 0xb4, 0xd6, 0x66, 0x8f, 0x35, 0x4c, 0x0c, 0x25,
	0xca, 0xbf, 0x27, 0xf1, 0x88, 0x15, 0x9f, 0xf3, 0x4b, 0xb7, 0x42, 0xb0, 0x82, 0xb3, 0xd2, 0x18,
	0xd2, 0xce, 0x8a, 0x7d, 0xa6, 0x58, 0x79, 0x1e, 0x31, 0x5d, 0x42, 0xf0, 0xc5, 0x17, 0x9b, 0x37,
	0x81, 0xc5, 0x5d, 0xe8, 0xdb, 0x54, 0xd9, 0xb9, 0x78, 0xc0, 0x9c, 0xcb, 0x02, 0x11, 0x8c, 0x32,
	0x38, 0xbc, 0xf8, 0x43, 0x66, 0x45, 0x4a, 0x31, 0x25, 0x89, 0xaa, 0xf2, 0xcb, 0x78, 0x72, 0x76,
	0x4d, 0x66, 0xa1, 0xa6, 0x84, 0x13, 0x78, 0xbc, 0xe5, 0x95, 0xe3, 0xb3, 0xe8, 0xe3, 0x57, 0xf4,
	0xe8, 0xf9, 0xa7, 0x0e, 0xc3, 0x8f, 0x87, 0x3f, 0x1f, 0xd8, 0x94, 0x92, 0xdb, 0x69, 0xae, 0x67,
	0x27, 0x7c, 0x9a, 0x4f, 0xfc, 0x69, 0x3e, 0x59, 0x7c, 0xfd, 0x7e, 0xc7, 0x5b, 0xdf, 0xfc, 0x17,
	0x00, 0x00, 0xff, 0xff, 0x6c, 0x5c, 0xf0, 0x3d, 0xb2, 0x05, 0x00, 0x00,
}
